> temp <- tempfile()
> download.file("http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip",temp)
trying URL 'http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip'
Content type 'application/zip' length 62556944 bytes (59.7 MB)
downloaded 59.7 MB

> unzip(temp, list = TRUE)
                                                           Name   Length
1                           UCI HAR Dataset/activity_labels.txt       80
2                                  UCI HAR Dataset/features.txt    15785
3                             UCI HAR Dataset/features_info.txt     2809
4                                    UCI HAR Dataset/README.txt     4453
5                                         UCI HAR Dataset/test/        0
6                        UCI HAR Dataset/test/Inertial Signals/        0
7     UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt  6041350
8     UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt  6041350
9     UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt  6041350
10   UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt  6041350
11   UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt  6041350
12   UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt  6041350
13   UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt  6041350
14   UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt  6041350
15   UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt  6041350
16                        UCI HAR Dataset/test/subject_test.txt     7934
17                              UCI HAR Dataset/test/X_test.txt 26458166
18                              UCI HAR Dataset/test/y_test.txt     5894
19                                       UCI HAR Dataset/train/        0
20                      UCI HAR Dataset/train/Inertial Signals/        0
21  UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt 15071600
22  UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt 15071600
23  UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt 15071600
24 UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt 15071600
25 UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt 15071600
26 UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt 15071600
27 UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt 15071600
28 UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt 15071600
29 UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt 15071600
30                      UCI HAR Dataset/train/subject_train.txt    20152
31                            UCI HAR Dataset/train/X_train.txt 66006256
32                            UCI HAR Dataset/train/y_train.txt    14704
                  Date
1  2012-10-10 15:55:00
2  2012-10-11 13:41:00
3  2012-10-15 15:44:00
4  2012-12-10 10:38:00
5  2012-11-29 17:01:00
6  2012-11-29 17:01:00
7  2012-11-29 15:08:00
8  2012-11-29 15:08:00
9  2012-11-29 15:08:00
10 2012-11-29 15:09:00
11 2012-11-29 15:09:00
12 2012-11-29 15:09:00
13 2012-11-29 15:08:00
14 2012-11-29 15:09:00
15 2012-11-29 15:09:00
16 2012-11-29 15:09:00
17 2012-11-29 15:25:00
18 2012-11-29 15:09:00
19 2012-11-29 17:01:00
20 2012-11-29 17:01:00
21 2012-11-29 15:08:00
22 2012-11-29 15:08:00
23 2012-11-29 15:08:00
24 2012-11-29 15:09:00
25 2012-11-29 15:09:00
26 2012-11-29 15:09:00
27 2012-11-29 15:08:00
28 2012-11-29 15:08:00
29 2012-11-29 15:08:00
30 2012-11-29 15:09:00
31 2012-11-29 15:25:00
32 2012-11-29 15:09:00
> YTest <- read.table(unzip(temp, "UCI HAR Dataset/test/y_test.txt"))
> XTest <- read.table(unzip(temp, "UCI HAR Dataset/test/X_test.txt"))
> SubjectTest <- read.table(unzip(temp, "UCI HAR Dataset/test/subject_test.txt"))
> YTrain <- read.table(unzip(temp, "UCI HAR Dataset/train/y_train.txt"))
> XTrain <- read.table(unzip(temp, "UCI HAR Dataset/train/X_train.txt"))
> SubjectTrain <- read.table(unzip(temp, "UCI HAR Dataset/train/subject_train.txt"))
> Features <- read.table(unzip(temp, "UCI HAR Dataset/features.txt"))
> colnames(XTrain) <- t(Features[2])
> colnames(XTest) <- t(Features[2])
> XTrain$activities <- YTrain[, 1]
> XTrain$participants <- SubjectTrain[, 1]
> XTest$activities <- YTest[, 1]
> XTest$participants <- SubjectTest[, 1]
> Mean <- grep("mean()", names(Master), value = FALSE, fixed = TRUE)
> Mean <- append(Mean, 471:477)
> InstrumentMeanMatrix <- Master[Mean]
> STD <- grep("std()", names(Master), value = FALSE)
> InstrumentSTDMatrix <- Master[STD]
> Master$activities <- as.character(Master$activities)
> Master$activities[Master$activities == 1] <- "Walking"
> Master$activities[Master$activities == 2] <- "Walking Upstairs"
> Master$activities[Master$activities == 3] <- "Walking Downstairs"
> Master$activities[Master$activities == 4] <- "Sitting"
> Master$activities[Master$activities == 5] <- "Standing"
> Master$activities[Master$activities == 6] <- "Laying"
> Master$activities <- as.factor(Master$activities)
> names(Master) 
  [1] "timeBodyAccelerator-mean()-X"                        
  [2] "timeBodyAccelerator-mean()-Y"                        
  [3] "timeBodyAccelerator-mean()-Z"                        
  [4] "timeBodyAccelerator-std()-X"                         
  [5] "timeBodyAccelerator-std()-Y"                         
  [6] "timeBodyAccelerator-std()-Z"                         
  [7] "timeBodyAccelerator-mad()-X"                         
  [8] "timeBodyAccelerator-mad()-Y"                         
  [9] "timeBodyAccelerator-mad()-Z"                         
 [10] "timeBodyAccelerator-max()-X"                         
 [11] "timeBodyAccelerator-max()-Y"                         
 [12] "timeBodyAccelerator-max()-Z"                         
 [13] "timeBodyAccelerator-min()-X"                         
 [14] "timeBodyAccelerator-min()-Y"                         
 [15] "timeBodyAccelerator-min()-Z"                         
 [16] "timeBodyAccelerator-sma()"                           
 [17] "timeBodyAccelerator-energy()-X"                      
 [18] "timeBodyAccelerator-energy()-Y"                      
 [19] "timeBodyAccelerator-energy()-Z"                      
 [20] "timeBodyAccelerator-iqr()-X"                         
 [21] "timeBodyAccelerator-iqr()-Y"                         
 [22] "timeBodyAccelerator-iqr()-Z"                         
 [23] "timeBodyAccelerator-entropy()-X"                     
 [24] "timeBodyAccelerator-entropy()-Y"                     
 [25] "timeBodyAccelerator-entropy()-Z"                     
 [26] "timeBodyAccelerator-arCoeff()-X,1"                   
 [27] "timeBodyAccelerator-arCoeff()-X,2"                   
 [28] "timeBodyAccelerator-arCoeff()-X,3"                   
 [29] "timeBodyAccelerator-arCoeff()-X,4"                   
 [30] "timeBodyAccelerator-arCoeff()-Y,1"                   
 [31] "timeBodyAccelerator-arCoeff()-Y,2"                   
 [32] "timeBodyAccelerator-arCoeff()-Y,3"                   
 [33] "timeBodyAccelerator-arCoeff()-Y,4"                   
 [34] "timeBodyAccelerator-arCoeff()-Z,1"                   
 [35] "timeBodyAccelerator-arCoeff()-Z,2"                   
 [36] "timeBodyAccelerator-arCoeff()-Z,3"                   
 [37] "timeBodyAccelerator-arCoeff()-Z,4"                   
 [38] "timeBodyAccelerator-correlation()-X,Y"               
 [39] "timeBodyAccelerator-correlation()-X,Z"               
 [40] "timeBodyAccelerator-correlation()-Y,Z"               
 [41] "timeGravityAccelerator-mean()-X"                     
 [42] "timeGravityAccelerator-mean()-Y"                     
 [43] "timeGravityAccelerator-mean()-Z"                     
 [44] "timeGravityAccelerator-std()-X"                      
 [45] "timeGravityAccelerator-std()-Y"                      
 [46] "timeGravityAccelerator-std()-Z"                      
 [47] "timeGravityAccelerator-mad()-X"                      
 [48] "timeGravityAccelerator-mad()-Y"                      
 [49] "timeGravityAccelerator-mad()-Z"                      
 [50] "timeGravityAccelerator-max()-X"                      
 [51] "timeGravityAccelerator-max()-Y"                      
 [52] "timeGravityAccelerator-max()-Z"                      
 [53] "timeGravityAccelerator-min()-X"                      
 [54] "timeGravityAccelerator-min()-Y"                      
 [55] "timeGravityAccelerator-min()-Z"                      
 [56] "timeGravityAccelerator-sma()"                        
 [57] "timeGravityAccelerator-energy()-X"                   
 [58] "timeGravityAccelerator-energy()-Y"                   
 [59] "timeGravityAccelerator-energy()-Z"                   
 [60] "timeGravityAccelerator-iqr()-X"                      
 [61] "timeGravityAccelerator-iqr()-Y"                      
 [62] "timeGravityAccelerator-iqr()-Z"                      
 [63] "timeGravityAccelerator-entropy()-X"                  
 [64] "timeGravityAccelerator-entropy()-Y"                  
 [65] "timeGravityAccelerator-entropy()-Z"                  
 [66] "timeGravityAccelerator-arCoeff()-X,1"                
 [67] "timeGravityAccelerator-arCoeff()-X,2"                
 [68] "timeGravityAccelerator-arCoeff()-X,3"                
 [69] "timeGravityAccelerator-arCoeff()-X,4"                
 [70] "timeGravityAccelerator-arCoeff()-Y,1"                
 [71] "timeGravityAccelerator-arCoeff()-Y,2"                
 [72] "timeGravityAccelerator-arCoeff()-Y,3"                
 [73] "timeGravityAccelerator-arCoeff()-Y,4"                
 [74] "timeGravityAccelerator-arCoeff()-Z,1"                
 [75] "timeGravityAccelerator-arCoeff()-Z,2"                
 [76] "timeGravityAccelerator-arCoeff()-Z,3"                
 [77] "timeGravityAccelerator-arCoeff()-Z,4"                
 [78] "timeGravityAccelerator-correlation()-X,Y"            
 [79] "timeGravityAccelerator-correlation()-X,Z"            
 [80] "timeGravityAccelerator-correlation()-Y,Z"            
 [81] "timeBodyAcceleratorJerk-mean()-X"                    
 [82] "timeBodyAcceleratorJerk-mean()-Y"                    
 [83] "timeBodyAcceleratorJerk-mean()-Z"                    
 [84] "timeBodyAcceleratorJerk-std()-X"                     
 [85] "timeBodyAcceleratorJerk-std()-Y"                     
 [86] "timeBodyAcceleratorJerk-std()-Z"                     
 [87] "timeBodyAcceleratorJerk-mad()-X"                     
 [88] "timeBodyAcceleratorJerk-mad()-Y"                     
 [89] "timeBodyAcceleratorJerk-mad()-Z"                     
 [90] "timeBodyAcceleratorJerk-max()-X"                     
 [91] "timeBodyAcceleratorJerk-max()-Y"                     
 [92] "timeBodyAcceleratorJerk-max()-Z"                     
 [93] "timeBodyAcceleratorJerk-min()-X"                     
 [94] "timeBodyAcceleratorJerk-min()-Y"                     
 [95] "timeBodyAcceleratorJerk-min()-Z"                     
 [96] "timeBodyAcceleratorJerk-sma()"                       
 [97] "timeBodyAcceleratorJerk-energy()-X"                  
 [98] "timeBodyAcceleratorJerk-energy()-Y"                  
 [99] "timeBodyAcceleratorJerk-energy()-Z"                  
[100] "timeBodyAcceleratorJerk-iqr()-X"                     
[101] "timeBodyAcceleratorJerk-iqr()-Y"                     
[102] "timeBodyAcceleratorJerk-iqr()-Z"                     
[103] "timeBodyAcceleratorJerk-entropy()-X"                 
[104] "timeBodyAcceleratorJerk-entropy()-Y"                 
[105] "timeBodyAcceleratorJerk-entropy()-Z"                 
[106] "timeBodyAcceleratorJerk-arCoeff()-X,1"               
[107] "timeBodyAcceleratorJerk-arCoeff()-X,2"               
[108] "timeBodyAcceleratorJerk-arCoeff()-X,3"               
[109] "timeBodyAcceleratorJerk-arCoeff()-X,4"               
[110] "timeBodyAcceleratorJerk-arCoeff()-Y,1"               
[111] "timeBodyAcceleratorJerk-arCoeff()-Y,2"               
[112] "timeBodyAcceleratorJerk-arCoeff()-Y,3"               
[113] "timeBodyAcceleratorJerk-arCoeff()-Y,4"               
[114] "timeBodyAcceleratorJerk-arCoeff()-Z,1"               
[115] "timeBodyAcceleratorJerk-arCoeff()-Z,2"               
[116] "timeBodyAcceleratorJerk-arCoeff()-Z,3"               
[117] "timeBodyAcceleratorJerk-arCoeff()-Z,4"               
[118] "timeBodyAcceleratorJerk-correlation()-X,Y"           
[119] "timeBodyAcceleratorJerk-correlation()-X,Z"           
[120] "timeBodyAcceleratorJerk-correlation()-Y,Z"           
[121] "timeBodyGyroscope-mean()-X"                          
[122] "timeBodyGyroscope-mean()-Y"                          
[123] "timeBodyGyroscope-mean()-Z"                          
[124] "timeBodyGyroscope-std()-X"                           
[125] "timeBodyGyroscope-std()-Y"                           
[126] "timeBodyGyroscope-std()-Z"                           
[127] "timeBodyGyroscope-mad()-X"                           
[128] "timeBodyGyroscope-mad()-Y"                           
[129] "timeBodyGyroscope-mad()-Z"                           
[130] "timeBodyGyroscope-max()-X"                           
[131] "timeBodyGyroscope-max()-Y"                           
[132] "timeBodyGyroscope-max()-Z"                           
[133] "timeBodyGyroscope-min()-X"                           
[134] "timeBodyGyroscope-min()-Y"                           
[135] "timeBodyGyroscope-min()-Z"                           
[136] "timeBodyGyroscope-sma()"                             
[137] "timeBodyGyroscope-energy()-X"                        
[138] "timeBodyGyroscope-energy()-Y"                        
[139] "timeBodyGyroscope-energy()-Z"                        
[140] "timeBodyGyroscope-iqr()-X"                           
[141] "timeBodyGyroscope-iqr()-Y"                           
[142] "timeBodyGyroscope-iqr()-Z"                           
[143] "timeBodyGyroscope-entropy()-X"                       
[144] "timeBodyGyroscope-entropy()-Y"                       
[145] "timeBodyGyroscope-entropy()-Z"                       
[146] "timeBodyGyroscope-arCoeff()-X,1"                     
[147] "timeBodyGyroscope-arCoeff()-X,2"                     
[148] "timeBodyGyroscope-arCoeff()-X,3"                     
[149] "timeBodyGyroscope-arCoeff()-X,4"                     
[150] "timeBodyGyroscope-arCoeff()-Y,1"                     
[151] "timeBodyGyroscope-arCoeff()-Y,2"                     
[152] "timeBodyGyroscope-arCoeff()-Y,3"                     
[153] "timeBodyGyroscope-arCoeff()-Y,4"                     
[154] "timeBodyGyroscope-arCoeff()-Z,1"                     
[155] "timeBodyGyroscope-arCoeff()-Z,2"                     
[156] "timeBodyGyroscope-arCoeff()-Z,3"                     
[157] "timeBodyGyroscope-arCoeff()-Z,4"                     
[158] "timeBodyGyroscope-correlation()-X,Y"                 
[159] "timeBodyGyroscope-correlation()-X,Z"                 
[160] "timeBodyGyroscope-correlation()-Y,Z"                 
[161] "timeBodyGyroscopeJerk-mean()-X"                      
[162] "timeBodyGyroscopeJerk-mean()-Y"                      
[163] "timeBodyGyroscopeJerk-mean()-Z"                      
[164] "timeBodyGyroscopeJerk-std()-X"                       
[165] "timeBodyGyroscopeJerk-std()-Y"                       
[166] "timeBodyGyroscopeJerk-std()-Z"                       
[167] "timeBodyGyroscopeJerk-mad()-X"                       
[168] "timeBodyGyroscopeJerk-mad()-Y"                       
[169] "timeBodyGyroscopeJerk-mad()-Z"                       
[170] "timeBodyGyroscopeJerk-max()-X"                       
[171] "timeBodyGyroscopeJerk-max()-Y"                       
[172] "timeBodyGyroscopeJerk-max()-Z"                       
[173] "timeBodyGyroscopeJerk-min()-X"                       
[174] "timeBodyGyroscopeJerk-min()-Y"                       
[175] "timeBodyGyroscopeJerk-min()-Z"                       
[176] "timeBodyGyroscopeJerk-sma()"                         
[177] "timeBodyGyroscopeJerk-energy()-X"                    
[178] "timeBodyGyroscopeJerk-energy()-Y"                    
[179] "timeBodyGyroscopeJerk-energy()-Z"                    
[180] "timeBodyGyroscopeJerk-iqr()-X"                       
[181] "timeBodyGyroscopeJerk-iqr()-Y"                       
[182] "timeBodyGyroscopeJerk-iqr()-Z"                       
[183] "timeBodyGyroscopeJerk-entropy()-X"                   
[184] "timeBodyGyroscopeJerk-entropy()-Y"                   
[185] "timeBodyGyroscopeJerk-entropy()-Z"                   
[186] "timeBodyGyroscopeJerk-arCoeff()-X,1"                 
[187] "timeBodyGyroscopeJerk-arCoeff()-X,2"                 
[188] "timeBodyGyroscopeJerk-arCoeff()-X,3"                 
[189] "timeBodyGyroscopeJerk-arCoeff()-X,4"                 
[190] "timeBodyGyroscopeJerk-arCoeff()-Y,1"                 
[191] "timeBodyGyroscopeJerk-arCoeff()-Y,2"                 
[192] "timeBodyGyroscopeJerk-arCoeff()-Y,3"                 
[193] "timeBodyGyroscopeJerk-arCoeff()-Y,4"                 
[194] "timeBodyGyroscopeJerk-arCoeff()-Z,1"                 
[195] "timeBodyGyroscopeJerk-arCoeff()-Z,2"                 
[196] "timeBodyGyroscopeJerk-arCoeff()-Z,3"                 
[197] "timeBodyGyroscopeJerk-arCoeff()-Z,4"                 
[198] "timeBodyGyroscopeJerk-correlation()-X,Y"             
[199] "timeBodyGyroscopeJerk-correlation()-X,Z"             
[200] "timeBodyGyroscopeJerk-correlation()-Y,Z"             
[201] "timeBodyAcceleratorMagnitude-mean()"                 
[202] "timeBodyAcceleratorMagnitude-std()"                  
[203] "timeBodyAcceleratorMagnitude-mad()"                  
[204] "timeBodyAcceleratorMagnitude-max()"                  
[205] "timeBodyAcceleratorMagnitude-min()"                  
[206] "timeBodyAcceleratorMagnitude-sma()"                  
[207] "timeBodyAcceleratorMagnitude-energy()"               
[208] "timeBodyAcceleratorMagnitude-iqr()"                  
[209] "timeBodyAcceleratorMagnitude-entropy()"              
[210] "timeBodyAcceleratorMagnitude-arCoeff()1"             
[211] "timeBodyAcceleratorMagnitude-arCoeff()2"             
[212] "timeBodyAcceleratorMagnitude-arCoeff()3"             
[213] "timeBodyAcceleratorMagnitude-arCoeff()4"             
[214] "timeGravityAcceleratorMagnitude-mean()"              
[215] "timeGravityAcceleratorMagnitude-std()"               
[216] "timeGravityAcceleratorMagnitude-mad()"               
[217] "timeGravityAcceleratorMagnitude-max()"               
[218] "timeGravityAcceleratorMagnitude-min()"               
[219] "timeGravityAcceleratorMagnitude-sma()"               
[220] "timeGravityAcceleratorMagnitude-energy()"            
[221] "timeGravityAcceleratorMagnitude-iqr()"               
[222] "timeGravityAcceleratorMagnitude-entropy()"           
[223] "timeGravityAcceleratorMagnitude-arCoeff()1"          
[224] "timeGravityAcceleratorMagnitude-arCoeff()2"          
[225] "timeGravityAcceleratorMagnitude-arCoeff()3"          
[226] "timeGravityAcceleratorMagnitude-arCoeff()4"          
[227] "timeBodyAcceleratorJerkMagnitude-mean()"             
[228] "timeBodyAcceleratorJerkMagnitude-std()"              
[229] "timeBodyAcceleratorJerkMagnitude-mad()"              
[230] "timeBodyAcceleratorJerkMagnitude-max()"              
[231] "timeBodyAcceleratorJerkMagnitude-min()"              
[232] "timeBodyAcceleratorJerkMagnitude-sma()"              
[233] "timeBodyAcceleratorJerkMagnitude-energy()"           
[234] "timeBodyAcceleratorJerkMagnitude-iqr()"              
[235] "timeBodyAcceleratorJerkMagnitude-entropy()"          
[236] "timeBodyAcceleratorJerkMagnitude-arCoeff()1"         
[237] "timeBodyAcceleratorJerkMagnitude-arCoeff()2"         
[238] "timeBodyAcceleratorJerkMagnitude-arCoeff()3"         
[239] "timeBodyAcceleratorJerkMagnitude-arCoeff()4"         
[240] "timeBodyGyroscopeMagnitude-mean()"                   
[241] "timeBodyGyroscopeMagnitude-std()"                    
[242] "timeBodyGyroscopeMagnitude-mad()"                    
[243] "timeBodyGyroscopeMagnitude-max()"                    
[244] "timeBodyGyroscopeMagnitude-min()"                    
[245] "timeBodyGyroscopeMagnitude-sma()"                    
[246] "timeBodyGyroscopeMagnitude-energy()"                 
[247] "timeBodyGyroscopeMagnitude-iqr()"                    
[248] "timeBodyGyroscopeMagnitude-entropy()"                
[249] "timeBodyGyroscopeMagnitude-arCoeff()1"               
[250] "timeBodyGyroscopeMagnitude-arCoeff()2"               
[251] "timeBodyGyroscopeMagnitude-arCoeff()3"               
[252] "timeBodyGyroscopeMagnitude-arCoeff()4"               
[253] "timeBodyGyroscopeJerkMagnitude-mean()"               
[254] "timeBodyGyroscopeJerkMagnitude-std()"                
[255] "timeBodyGyroscopeJerkMagnitude-mad()"                
[256] "timeBodyGyroscopeJerkMagnitude-max()"                
[257] "timeBodyGyroscopeJerkMagnitude-min()"                
[258] "timeBodyGyroscopeJerkMagnitude-sma()"                
[259] "timeBodyGyroscopeJerkMagnitude-energy()"             
[260] "timeBodyGyroscopeJerkMagnitude-iqr()"                
[261] "timeBodyGyroscopeJerkMagnitude-entropy()"            
[262] "timeBodyGyroscopeJerkMagnitude-arCoeff()1"           
[263] "timeBodyGyroscopeJerkMagnitude-arCoeff()2"           
[264] "timeBodyGyroscopeJerkMagnitude-arCoeff()3"           
[265] "timeBodyGyroscopeJerkMagnitude-arCoeff()4"           
[266] "frequencyBodyAccelerator-mean()-X"                   
[267] "frequencyBodyAccelerator-mean()-Y"                   
[268] "frequencyBodyAccelerator-mean()-Z"                   
[269] "frequencyBodyAccelerator-std()-X"                    
[270] "frequencyBodyAccelerator-std()-Y"                    
[271] "frequencyBodyAccelerator-std()-Z"                    
[272] "frequencyBodyAccelerator-mad()-X"                    
[273] "frequencyBodyAccelerator-mad()-Y"                    
[274] "frequencyBodyAccelerator-mad()-Z"                    
[275] "frequencyBodyAccelerator-max()-X"                    
[276] "frequencyBodyAccelerator-max()-Y"                    
[277] "frequencyBodyAccelerator-max()-Z"                    
[278] "frequencyBodyAccelerator-min()-X"                    
[279] "frequencyBodyAccelerator-min()-Y"                    
[280] "frequencyBodyAccelerator-min()-Z"                    
[281] "frequencyBodyAccelerator-sma()"                      
[282] "frequencyBodyAccelerator-energy()-X"                 
[283] "frequencyBodyAccelerator-energy()-Y"                 
[284] "frequencyBodyAccelerator-energy()-Z"                 
[285] "frequencyBodyAccelerator-iqr()-X"                    
[286] "frequencyBodyAccelerator-iqr()-Y"                    
[287] "frequencyBodyAccelerator-iqr()-Z"                    
[288] "frequencyBodyAccelerator-entropy()-X"                
[289] "frequencyBodyAccelerator-entropy()-Y"                
[290] "frequencyBodyAccelerator-entropy()-Z"                
[291] "frequencyBodyAccelerator-maxInds-X"                  
[292] "frequencyBodyAccelerator-maxInds-Y"                  
[293] "frequencyBodyAccelerator-maxInds-Z"                  
[294] "frequencyBodyAccelerator-meanFreq()-X"               
[295] "frequencyBodyAccelerator-meanFreq()-Y"               
[296] "frequencyBodyAccelerator-meanFreq()-Z"               
[297] "frequencyBodyAccelerator-skewness()-X"               
[298] "frequencyBodyAccelerator-kurtosis()-X"               
[299] "frequencyBodyAccelerator-skewness()-Y"               
[300] "frequencyBodyAccelerator-kurtosis()-Y"               
[301] "frequencyBodyAccelerator-skewness()-Z"               
[302] "frequencyBodyAccelerator-kurtosis()-Z"               
[303] "frequencyBodyAccelerator-bandsEnergy()-1,8"          
[304] "frequencyBodyAccelerator-bandsEnergy()-9,16"         
[305] "frequencyBodyAccelerator-bandsEnergy()-17,24"        
[306] "frequencyBodyAccelerator-bandsEnergy()-25,32"        
[307] "frequencyBodyAccelerator-bandsEnergy()-33,40"        
[308] "frequencyBodyAccelerator-bandsEnergy()-41,48"        
[309] "frequencyBodyAccelerator-bandsEnergy()-49,56"        
[310] "frequencyBodyAccelerator-bandsEnergy()-57,64"        
[311] "frequencyBodyAccelerator-bandsEnergy()-1,16"         
[312] "frequencyBodyAccelerator-bandsEnergy()-17,32"        
[313] "frequencyBodyAccelerator-bandsEnergy()-33,48"        
[314] "frequencyBodyAccelerator-bandsEnergy()-49,64"        
[315] "frequencyBodyAccelerator-bandsEnergy()-1,24"         
[316] "frequencyBodyAccelerator-bandsEnergy()-25,48"        
[317] "frequencyBodyAcceleratorJerk-mean()-X"               
[318] "frequencyBodyAcceleratorJerk-mean()-Y"               
[319] "frequencyBodyAcceleratorJerk-mean()-Z"               
[320] "frequencyBodyAcceleratorJerk-std()-X"                
[321] "frequencyBodyAcceleratorJerk-std()-Y"                
[322] "frequencyBodyAcceleratorJerk-std()-Z"                
[323] "frequencyBodyAcceleratorJerk-mad()-X"                
[324] "frequencyBodyAcceleratorJerk-mad()-Y"                
[325] "frequencyBodyAcceleratorJerk-mad()-Z"                
[326] "frequencyBodyAcceleratorJerk-max()-X"                
[327] "frequencyBodyAcceleratorJerk-max()-Y"                
[328] "frequencyBodyAcceleratorJerk-max()-Z"                
[329] "frequencyBodyAcceleratorJerk-min()-X"                
[330] "frequencyBodyAcceleratorJerk-min()-Y"                
[331] "frequencyBodyAcceleratorJerk-min()-Z"                
[332] "frequencyBodyAcceleratorJerk-sma()"                  
[333] "frequencyBodyAcceleratorJerk-energy()-X"             
[334] "frequencyBodyAcceleratorJerk-energy()-Y"             
[335] "frequencyBodyAcceleratorJerk-energy()-Z"             
[336] "frequencyBodyAcceleratorJerk-iqr()-X"                
[337] "frequencyBodyAcceleratorJerk-iqr()-Y"                
[338] "frequencyBodyAcceleratorJerk-iqr()-Z"                
[339] "frequencyBodyAcceleratorJerk-entropy()-X"            
[340] "frequencyBodyAcceleratorJerk-entropy()-Y"            
[341] "frequencyBodyAcceleratorJerk-entropy()-Z"            
[342] "frequencyBodyAcceleratorJerk-maxInds-X"              
[343] "frequencyBodyAcceleratorJerk-maxInds-Y"              
[344] "frequencyBodyAcceleratorJerk-maxInds-Z"              
[345] "frequencyBodyAcceleratorJerk-meanFreq()-X"           
[346] "frequencyBodyAcceleratorJerk-meanFreq()-Y"           
[347] "frequencyBodyAcceleratorJerk-meanFreq()-Z"           
[348] "frequencyBodyAcceleratorJerk-skewness()-X"           
[349] "frequencyBodyAcceleratorJerk-kurtosis()-X"           
[350] "frequencyBodyAcceleratorJerk-skewness()-Y"           
[351] "frequencyBodyAcceleratorJerk-kurtosis()-Y"           
[352] "frequencyBodyAcceleratorJerk-skewness()-Z"           
[353] "frequencyBodyAcceleratorJerk-kurtosis()-Z"           
[354] "frequencyBodyAcceleratorJerk-bandsEnergy()-1,8"      
[355] "frequencyBodyAcceleratorJerk-bandsEnergy()-9,16"     
[356] "frequencyBodyAcceleratorJerk-bandsEnergy()-17,24"    
[357] "frequencyBodyAcceleratorJerk-bandsEnergy()-25,32"    
[358] "frequencyBodyAcceleratorJerk-bandsEnergy()-33,40"    
[359] "frequencyBodyAcceleratorJerk-bandsEnergy()-41,48"    
[360] "frequencyBodyAcceleratorJerk-bandsEnergy()-49,56"    
[361] "frequencyBodyAcceleratorJerk-bandsEnergy()-57,64"    
[362] "frequencyBodyAcceleratorJerk-bandsEnergy()-1,16"     
[363] "frequencyBodyAcceleratorJerk-bandsEnergy()-17,32"    
[364] "frequencyBodyAcceleratorJerk-bandsEnergy()-33,48"    
[365] "frequencyBodyAcceleratorJerk-bandsEnergy()-49,64"    
[366] "frequencyBodyAcceleratorJerk-bandsEnergy()-1,24"     
[367] "frequencyBodyAcceleratorJerk-bandsEnergy()-25,48"    
[368] "frequencyBodyGyroscope-mean()-X"                     
[369] "frequencyBodyGyroscope-mean()-Y"                     
[370] "frequencyBodyGyroscope-mean()-Z"                     
[371] "frequencyBodyGyroscope-std()-X"                      
[372] "frequencyBodyGyroscope-std()-Y"                      
[373] "frequencyBodyGyroscope-std()-Z"                      
[374] "frequencyBodyGyroscope-mad()-X"                      
[375] "frequencyBodyGyroscope-mad()-Y"                      
[376] "frequencyBodyGyroscope-mad()-Z"                      
[377] "frequencyBodyGyroscope-max()-X"                      
[378] "frequencyBodyGyroscope-max()-Y"                      
[379] "frequencyBodyGyroscope-max()-Z"                      
[380] "frequencyBodyGyroscope-min()-X"                      
[381] "frequencyBodyGyroscope-min()-Y"                      
[382] "frequencyBodyGyroscope-min()-Z"                      
[383] "frequencyBodyGyroscope-sma()"                        
[384] "frequencyBodyGyroscope-energy()-X"                   
[385] "frequencyBodyGyroscope-energy()-Y"                   
[386] "frequencyBodyGyroscope-energy()-Z"                   
[387] "frequencyBodyGyroscope-iqr()-X"                      
[388] "frequencyBodyGyroscope-iqr()-Y"                      
[389] "frequencyBodyGyroscope-iqr()-Z"                      
[390] "frequencyBodyGyroscope-entropy()-X"                  
[391] "frequencyBodyGyroscope-entropy()-Y"                  
[392] "frequencyBodyGyroscope-entropy()-Z"                  
[393] "frequencyBodyGyroscope-maxInds-X"                    
[394] "frequencyBodyGyroscope-maxInds-Y"                    
[395] "frequencyBodyGyroscope-maxInds-Z"                    
[396] "frequencyBodyGyroscope-meanFreq()-X"                 
[397] "frequencyBodyGyroscope-meanFreq()-Y"                 
[398] "frequencyBodyGyroscope-meanFreq()-Z"                 
[399] "frequencyBodyGyroscope-skewness()-X"                 
[400] "frequencyBodyGyroscope-kurtosis()-X"                 
[401] "frequencyBodyGyroscope-skewness()-Y"                 
[402] "frequencyBodyGyroscope-kurtosis()-Y"                 
[403] "frequencyBodyGyroscope-skewness()-Z"                 
[404] "frequencyBodyGyroscope-kurtosis()-Z"                 
[405] "frequencyBodyGyroscope-bandsEnergy()-1,8"            
[406] "frequencyBodyGyroscope-bandsEnergy()-9,16"           
[407] "frequencyBodyGyroscope-bandsEnergy()-17,24"          
[408] "frequencyBodyGyroscope-bandsEnergy()-25,32"          
[409] "frequencyBodyGyroscope-bandsEnergy()-33,40"          
[410] "frequencyBodyGyroscope-bandsEnergy()-41,48"          
[411] "frequencyBodyGyroscope-bandsEnergy()-49,56"          
[412] "frequencyBodyGyroscope-bandsEnergy()-57,64"          
[413] "frequencyBodyGyroscope-bandsEnergy()-1,16"           
[414] "frequencyBodyGyroscope-bandsEnergy()-17,32"          
[415] "frequencyBodyGyroscope-bandsEnergy()-33,48"          
[416] "frequencyBodyGyroscope-bandsEnergy()-49,64"          
[417] "frequencyBodyGyroscope-bandsEnergy()-1,24"           
[418] "frequencyBodyGyroscope-bandsEnergy()-25,48"          
[419] "frequencyBodyAcceleratorMagnitude-mean()"            
[420] "frequencyBodyAcceleratorMagnitude-std()"             
[421] "frequencyBodyAcceleratorMagnitude-mad()"             
[422] "frequencyBodyAcceleratorMagnitude-max()"             
[423] "frequencyBodyAcceleratorMagnitude-min()"             
[424] "frequencyBodyAcceleratorMagnitude-sma()"             
[425] "frequencyBodyAcceleratorMagnitude-energy()"          
[426] "frequencyBodyAcceleratorMagnitude-iqr()"             
[427] "frequencyBodyAcceleratorMagnitude-entropy()"         
[428] "frequencyBodyAcceleratorMagnitude-maxInds"           
[429] "frequencyBodyAcceleratorMagnitude-meanFreq()"        
[430] "frequencyBodyAcceleratorMagnitude-skewness()"        
[431] "frequencyBodyAcceleratorMagnitude-kurtosis()"        
[432] "frequencyBodyBodyAcceleratorJerkMagnitude-mean()"    
[433] "frequencyBodyBodyAcceleratorJerkMagnitude-std()"     
[434] "frequencyBodyBodyAcceleratorJerkMagnitude-mad()"     
[435] "frequencyBodyBodyAcceleratorJerkMagnitude-max()"     
[436] "frequencyBodyBodyAcceleratorJerkMagnitude-min()"     
[437] "frequencyBodyBodyAcceleratorJerkMagnitude-sma()"     
[438] "frequencyBodyBodyAcceleratorJerkMagnitude-energy()"  
[439] "frequencyBodyBodyAcceleratorJerkMagnitude-iqr()"     
[440] "frequencyBodyBodyAcceleratorJerkMagnitude-entropy()" 
[441] "frequencyBodyBodyAcceleratorJerkMagnitude-maxInds"   
[442] "frequencyBodyBodyAcceleratorJerkMagnitude-meanFreq()"
[443] "frequencyBodyBodyAcceleratorJerkMagnitude-skewness()"
[444] "frequencyBodyBodyAcceleratorJerkMagnitude-kurtosis()"
[445] "frequencyBodyBodyGyroscopeMagnitude-mean()"          
[446] "frequencyBodyBodyGyroscopeMagnitude-std()"           
[447] "frequencyBodyBodyGyroscopeMagnitude-mad()"           
[448] "frequencyBodyBodyGyroscopeMagnitude-max()"           
[449] "frequencyBodyBodyGyroscopeMagnitude-min()"           
[450] "frequencyBodyBodyGyroscopeMagnitude-sma()"           
[451] "frequencyBodyBodyGyroscopeMagnitude-energy()"        
[452] "frequencyBodyBodyGyroscopeMagnitude-iqr()"           
[453] "frequencyBodyBodyGyroscopeMagnitude-entropy()"       
[454] "frequencyBodyBodyGyroscopeMagnitude-maxInds"         
[455] "frequencyBodyBodyGyroscopeMagnitude-meanFreq()"      
[456] "frequencyBodyBodyGyroscopeMagnitude-skewness()"      
[457] "frequencyBodyBodyGyroscopeMagnitude-kurtosis()"      
[458] "frequencyBodyBodyGyroscopeJerkMagnitude-mean()"      
[459] "frequencyBodyBodyGyroscopeJerkMagnitude-std()"       
[460] "frequencyBodyBodyGyroscopeJerkMagnitude-mad()"       
[461] "frequencyBodyBodyGyroscopeJerkMagnitude-max()"       
[462] "frequencyBodyBodyGyroscopeJerkMagnitude-min()"       
[463] "frequencyBodyBodyGyroscopeJerkMagnitude-sma()"       
[464] "frequencyBodyBodyGyroscopeJerkMagnitude-energy()"    
[465] "frequencyBodyBodyGyroscopeJerkMagnitude-iqr()"       
[466] "frequencyBodyBodyGyroscopeJerkMagnitude-entropy()"   
[467] "frequencyBodyBodyGyroscopeJerkMagnitude-maxInds"     
[468] "frequencyBodyBodyGyroscopeJerkMagnitude-meanFreq()"  
[469] "frequencyBodyBodyGyroscopeJerkMagnitude-skewness()"  
[470] "frequencyBodyBodyGyroscopeJerkMagnitude-kurtosis()"  
[471] "angle(tBodyAcceleratorMean,gravity)"                 
[472] "angle(tBodyAcceleratorJerkMean),gravityMean)"        
[473] "angle(tBodyGyroscopeMean,gravityMean)"               
[474] "angle(tBodyGyroscopeJerkMean,gravityMean)"           
[475] "angle(X,gravityMean)"                                
[476] "angle(Y,gravityMean)"                                
[477] "angle(Z,gravityMean)"                                
[478] "activities"                                          
[479] "participants"                                        
> names(Master) <- gsub("Acc", "Accelerator", names(Master))
> names(Master) <- gsub("Mag", "Magnitude", names(Master))
> names(Master) <- gsub("Gyro", "Gyroscope", names(Master))
> names(Master) <- gsub("^t", "time", names(Master))
> names(Master) <- gsub("^f", "frequency", names(Master))
> Master$participants <- as.character(Master$participants)
> Master$participants[Master$participants == 1] <- "Participant 1"
> Master$participants[Master$participants == 2] <- "Participant 2"
> Master$participants[Master$participants == 3] <- "Participant 3"
> Master$participants[Master$participants == 4] <- "Participant 4"
> Master$participants[Master$participants == 5] <- "Participant 5"
> Master$participants[Master$participants == 6] <- "Participant 6"
> Master$participants[Master$participants == 7] <- "Participant 7"
> Master$participants[Master$participants == 8] <- "Participant 8"
> Master$participants[Master$participants == 9] <- "Participant 9"
> Master$participants[Master$participants == 10] <- "Participant 10"
> Master$participants[Master$participants == 11] <- "Participant 11"
> Master$participants[Master$participants == 12] <- "Participant 12"
> Master$participants[Master$participants == 13] <- "Participant 13"
> Master$participants[Master$participants == 14] <- "Participant 14"
> Master$participants[Master$participants == 15] <- "Participant 15"
> Master$participants[Master$participants == 16] <- "Participant 16"
> Master$participants[Master$participants == 17] <- "Participant 17"
> Master$participants[Master$participants == 18] <- "Participant 18"
> Master$participants[Master$participants == 19] <- "Participant 19"
> Master$participants[Master$participants == 20] <- "Participant 20"
> Master$participants[Master$participants == 21] <- "Participant 21"
> Master$participants[Master$participants == 22] <- "Participant 22"
> Master$participants[Master$participants == 23] <- "Participant 23"
> Master$participants[Master$participants == 24] <- "Participant 24"
> Master$participants[Master$participants == 25] <- "Participant 25"
> Master$participants[Master$participants == 26] <- "Participant 26"
> Master$participants[Master$participants == 27] <- "Participant 27"
> Master$participants[Master$participants == 28] <- "Participant 28"
> Master$participants[Master$participants == 29] <- "Participant 29"
> Master$participants[Master$participants == 30] <- "Participant 30"
> Master$participants <- as.factor(Master$participants)
> Master.dt <- data.table(Master)
> TidyData <- Master.dt[, lapply(.SD, mean), by = 'participants,activities']
> write.table(TidyData, file = "Tidy.txt", row.names = FALSE
